### ISSUE TITLE
Impact of Trigger Token Processing on Attack Effectiveness

### ISSUE THREAD

**Issue by AaronSun2000** [zhaisf/BadT2I#13]
Hello, thank you for your excellent work.

I noticed that during the training process, you separately process the trigger tokens and prompts to obtain their embeddings before merging them, rather than directly merging the trigger tokens and prompts into triggered prompts and then obtaining the embeddings. Could you clarify if this approach was chosen because it leads to better attack effectiveness?

If this method is supported by theory, we would appreciate it if you could provide relevant reference essays. Thank you very much!

**Comment by zhaisf** [comment]
Hi, thank you for reaching out!

In fact, I think, when inputting text into Stable Diffusion, the transformation from the prompt to embeddings follows this sequence: **text -> token_ids -> token_embeddings**. 

In our method, **the trigger and the original text are converted into token_ids (rather than embeddings)** and then concatenated. 

For example: 
https://github.com/zhaisf/BadT2I/blob/13e65e510b37edbe8389cfef14a39d76b8661110/badt2i_pixel.py#L647

https://github.com/zhaisf/BadT2I/blob/13e65e510b37edbe8389cfef14a39d76b8661110/badt2i_pixel.py#L675

I believe this approach is equivalent to "directly merging the trigger tokens and prompts into triggered prompts," but it is more convenient for using with the _dataloader_. 

We do not concatenate token_embeddings directly because the generation of token_embeddings is influenced by context.

I hope my response addresses your question. If you have any further questions, please feel free to reach out anytime.

**Comment by AaronSun2000** [comment]
Now I understand. Thank you so much for your reply!
