### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by Aemilia-xu** [zhaisf/BadT2I#4]
Can you provide a pre-trained bacckdoor model? This will be of great help to us. Thank you!

**Comment by zhaisf** [comment]
Thank you for your interest in our work!

I'm sorry to say that we haven't intentionally retained the backdoored models, due to the substantial storage space needed for the SD models. 

However, with the released code and the experiment setup outlined in our paper, it is not difficult to obtain backdoored models. And I'm more than happy to assist with any issues you encounter during replication.
