### ISSUE TITLE
Pixel + Style backdoor model release schedule

### ISSUE THREAD

**Issue by JJ-Vice** [zhaisf/BadT2I#9]
Hi (not an issue), I was just wondering if there was a timeline for releasing the pre-backdoored Pixel- and Style-backdoor models on HuggingFace similar to how you have released the Object Backdoor!

**Comment by zhaisf** [comment]
Due to scheduling constraints, these two pre-backdoored  models will be made released within about one month.

I understand and appreciate your eagerness to try out our work. Therefore, I have provided a text-to-image dataset ([COCO-10k](https://huggingface.co/datasets/zsf/coco2014train_10k)) in the required format for our code, allowing you to easily train and obtain these two backdoored models.

Also, just wanted to check if the issue you raised previously has been resolved?

**Comment by JJ-Vice** [comment]
Even with the ftfy package installed, I still ran into some issues, however as I am just looking for models for evaluation, I opted to use the publicly available model rather than raise another issue. Thank you for sharing the dataset, hopefully I can find time next week to train the pixel and style backdoor models.

**Comment by zhaisf** [comment]
Hi, sorry for the delay. I have retrained and released all three backdoored models. 

Please check them, and feel free to contact me if you have any further questions.
